[build]
publish = "."
command = "npm run build"

[functions]
[functions.daily-report]
schedule = "0 8 * * *"

[functions.event-reminder]
schedule = "0 * * * *"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"